global:
  scrape_interval: 15s  # Set the scrape interval to 15 seconds
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - '192.168.1.80:9093'
rule_files:
  - 'alerting.rules.yml'
scrape_configs:
  - job_name: 'capstone-app'
    static_configs:
      - targets: ['192.168.1.80:9113']
